# 文件：config.yaml（请放置在项目根目录）
# 这是配置文件，控制每个处理模块是否启用，以及它们的参数。
# 新手建议：通过修改这个文件来测试不同处理效果。

raw:   
  input_dir: "D:\\Code\\ISP_Framework\\image"
  width: 2048
  height: 2048
  sensor_bit_depth: 10
  raw_to_16bit_scale_factor: 64

fisheye_mask:
  enable: false
  center: [1456, 1456]
  radius: 1456

blc:
  enable: true 
  black_level: 64 

denoise_clip:
  enable: false
  threshold: 10

lsc:
  enable: true
  model_type: "cosine_fourth"
  strength: 0.3
  pixel_size_um: 1.4
  focal_length_mm: 4.0

demosaic:
  enable: true
  method: "opencv_ea"
  bayer_pattern: "bggr"

wb:
  enable: true
  method: "gray_world"  # 可选: "manual", "gray_world", "white_patch"
  gains: [1.5, 1.0, 1.3]  # manual模式下的增益
  wb_min_luminance_threshold: 0.05  # gray_world最小亮度阈值
  wb_max_luminance_threshold: 0.99  # gray_world最大亮度阈值
  max_gain: 3.0  # 最大增益限制
  min_gain: 0.3  # 最小增益限制
  white_patch_percentile: 99.5  # white_patch算法的百分位数

denoise:
  enable: false  # 完全禁用去噪

ccm:
  enable: true   
  matrix: [[1.2, -0.1, -0.1],
           [-0.05, 1.2, -0.15],   
           [0.0, -0.1, 1.1]]
  
  highlight_threshold: 0.7
  saturation_boost: 1.8          # 从1.3提高到1.8

chroma_denoise:
  enable: false
  luma_threshold: 0.2
  chroma_strength: 0.7
  
gamma:
  enable: true   
  value: 2.2
  curve_type: "s_curve"
  midtone_boost: 0.05           # 降低到0.05，避免过度

tonemapping:
  enable: true 
  lift: 0.1           # 提高lift，提亮暗部
  roll: 0.8           # 提高roll，减少压缩
  compress: 0.45      # 降低compress，减少压缩强度
  contrast: 1.1       # 增加对比度
  brightness: 1.05    # 轻微提亮

sharpen:
  enable: false
  method: "unsharp_masking"
  blur_kernel_size: 3
  strength: 1.5

super_resolution:
  enable: false
  scale_factor: 2.0
  upscale_method: "bicubic"
  sharpen_enable: true
  sharpen_amount: 0.8
  sharpen_radius: 1.0

output:   
  path: "output/result.png"
  output_dir: "output/results/"
  debug_dir: "output/debug_steps/"
  dither_strength: 0.5

noise_estimation:
  enable: false
  dark_threshold: 0.1

color_space_conversion:
  enable: false
  input_space: "sRGB"
  output_space: "rec2020"
  gamut_mapping: "compress"

# 位深管理配置
bit_depth_management:
  raw_input: 10          # 传感器原生10bit
  blc_output: 12         # BLC后扩展到12bit
  lsc_output: 12         # LSC保持12bit
  demosaic_output: "float32"  # Demosaic转浮点
  wb_output: "float32"   # WB HDR处理
  ccm_output: "float32"  # CCM矩阵运算
  final_output: "float32" # 最终0-1范围
