# 文件：config.yaml（请放置在项目根目录） """ # 这是配置文件，控制每个处理模块是否启用，以及它们的参数。 # 新手建议：通过修改这个文件来测试不同处理效果。 
 raw:   
  #path: "./BGGR.raw"  # 输入 RAW 图像路径 
  input_dir: "D:\\Code\\ISP_Framework\\image"
  width: 2048
  height: 2048
  sensor_bit_depth: 10
  raw_to_16bit_scale_factor: 64 # 例如，如果你的 RAW 是 10-bit，这里填 64
  


 fisheye_mask:
  enable: false
  center: [1456, 1456]
  radius: 1456

 blc:  # 黑电平校正（Black Level Correction）   
  enable: true 
  black_level: 64 

 denoise_clip:
  enable: false
  threshold: 10


 lsc:
  enable: false
  # LSC 模型类型：
  # 'linear': 简单的线性增益 (1 + strength * distance)
  # 'quadratic': 二次函数增益 (1 + strength * distance^2) - 推荐，更平滑
  # 'cosine_fourth': 余弦四次方近似增益 (1 + strength * distance^4) - 模拟更真实的晕影
  model_type: quadratic 
  # 增益强度：值越大，边缘提亮越多
  strength: 0.3 # 0.1 到 0.5 之间通常比较合适
  # 如果你使用了 cosine_fourth 模型，可能需要调整这个 K 值
  # cosine_fourth_k: 0.5 
  # 用于 LSC 裁剪的上限值。
  # 应该与 demosaic 中使用的 `max_raw_sensor_value_mapped_to_uint16` 相同
  # 如果你的 raw_loader 读出的是 uint16，且已左移填充，那么填 65472 或 65535
  # max_value_for_clip: 65472 # (可选，如果 raw_to_16bit_scale_factor 导致最大值改变)


 demosaic: #去马赛克
  enable: true   
  method: "opencv" 
   #这个值至关重要！它应该是你的 RAW 传感器数据在被读取并转换为 uint16 后，
  # 能够达到的最大理论值。
  # 如果是 10bit RAW 左移 6bit 存入 uint16，那么这里就是 1023 * (2**6) = 65472
  # 如果是 12bit RAW 左移 4bit 存入 uint16，那么这里就是 4095 * (2**4) = 65520
  # 如果是标准的 16bit RAW，那么就是 65535
   # 请根据你的原始 RAW 数据的实际位深来设置此值。
  bayer_pattern: "rggb"  # Bayer 模式，常见的有 'bggr', 'gbrg', 'grbg', 'rggb'




 wb:   # 白平衡（White Balance）   
  enable: true
  # White balance method: 'manual', 'gray_world', 'max_rgb'
  method: gray_world 
  # 如果 method 是 'manual'，则使用下面的 gains
  gains: [1.5, 1.0, 1.3] 
  # 如果是 'gray_world' 或 'max_rgb'，这些 gains 会被覆盖git
  # --- 添加这些用于亮度筛选的新参数 ---
  # 用于白平衡计算的像素最小亮度阈值
  # 平均RGB值低于此值的像素将被排除 (例如，暗部噪声)
  wb_min_luminance_threshold: 0.05 # 根据需要调整此值 (例如，从 0.01 到 0.1)

  # 用于白平衡计算的像素最大亮度阈值
  # 平均RGB值高于此值的像素将被排除 (例如，饱和的高光)
  wb_max_luminance_threshold: 0.99 # 根据需要调整此值 (例如，从 0.95 到 0.99)


 denoise:  #去噪
  enable: false
  # 去噪方法：'gaussian', 'bilateral', 'median', 'nl_means'
  method:  nl_means 
  # 高斯模糊和中值滤波参数
  kernel_size: 7 # 必须是奇数，如 3, 5, 7, ...
  sigma_x: 0    # 高斯模糊X方向标准差，0表示根据核大小计算
  # 双边滤波参数 (如果 method 为 'bilateral')
  diameter: 7       # 邻域直径
  sigma_color: 50   # 颜色相似度标准差 (0-255)
  sigma_space: 50   # 空间相似度标准差 (0-255)
  # 'nl_means' (非局部均值) 参数
  h_param: 3       # 关键强度参数。值越大，去噪越强，但细节损失也越大。从 10-20 之间尝试。
  h_color_param: 3 # 颜色强度参数，通常与 h_param 相同。
  template_window_size: 7 # 小窗口，用于定义补丁（patch）
  search_window_size: 21  # 大窗口，用于搜索相似补丁的范围




 ccm:  # 颜色矩阵（Color Correction Matrix）   
  enable: true   
  matrix: [[1.9, -0.5, -0.4],   # R_out = 1.8*R_in - 0.4*G_in - 0.4*B_in  (和为 1.0)
         [-0.3, 1.6, -0.3],   # G_out = -0.3*R_in + 1.6*G_in - 0.3*B_in (和为 1.0)
         [-0.2, -0.6, 1.8]] 

 
 chroma_denoise: # 色彩去噪
  enable: false
  luma_threshold: 0.2
  chroma_strength: 0.7

  
 gamma:  # Gamma 校正   
  enable: true   
  value: 2.2 



 tonemapping:
  enable: true 
  # 暗部提亮 / 整体曝光：
  lift: 0.05   # 默认值：提供 moderate 的整体亮度提升。如果仍嫌暗，可增大。
                # 范围建议：0.0 到 1.0。

  # 高光压制（避免过度压缩）：
  roll: 0.7     # 默认值：确保高光压缩点较高。
                # 如果高光仍过曝，可稍微减小；如果高光仍偏暗，可增大。
                # 范围建议：0.5 到 1.5。
  compress: 0.55 # 默认值：降低高光压缩强度。
                # 如果高光仍过曝，可稍微增大；如果高光暗淡，可减小。
                # 范围建议：0.0 (最弱压缩) 到 0.8 (较强压缩)。

  # 对比度：
  contrast: 1.0   # 默认值：中性对比度。
                  # 如果画面平淡，增大至 1.2-1.5。如果画面过硬，减小至 0.8-0.9。
                  # 范围建议：0.5 到 2.0。

  # 整体亮度乘数：
  brightness: 1.0 # 默认值：中性。
                  # 如果上述调整后仍偏暗，可增大至 1.2-2.0。这是最直接的亮度提升。
                  # 范围建议：0.5 到 2.5。
 



 sharpen:  #锐化
  enable: false
  # 锐化方法：'unsharp_masking' (目前只实现了这一种)
  method: unsharp_masking 
  # 非锐化掩蔽参数
  blur_kernel_size: 3 # 用于生成模糊图像的核大小，必须是奇数，如 3, 5, 7, ...
  strength: 1.5      # 锐化强度，通常 0.5 到 2.0 之间。过大会产生光晕或噪声


 super_resolution:
  enable: false        # 是否启用超分辨阶段 (true/false)
  scale_factor: 2.0   # 放大倍数，例如 2.0 (2倍), 4.0 (4倍)。必须大于 1.0。
  upscale_method: bicubic # 插值方法: 'bicubic' (双三次，推荐), 'nearest' (最近邻), 'bilinear' (双线性)
  sharpen_enable: true # 是否在放大后应用锐化 (不锐化可能看起来模糊)
  sharpen_amount: 0.8 # 锐化强度。值越大越锐利，但可能引入光晕或噪点。推荐 0.5-1.5。
  sharpen_radius: 1.0 # 锐化半径。值越大影响范围越大，但可能导致不自然。推荐 0.5-2.0。




 output:   
  path: "output/result.png"      # 最终输出图像路径   
  debug_dir: "output/"           # 每个步骤的中间图保存目录 """
  dither_strength: 0.5 # 抖动强度，通常在 0.5 到 1.0 之间尝试。设置为 0 则禁用抖动。

