bit_depth_management:
  display_ready: float32
  enable_dithering: true
  final_output: 8
  hdr_range:
  - 0.0
  - 8.0
  linear_hdr: float32
  noise_floor_lsb: 1.5
  raw_processing: 16
  sensor_native: 10
blc:
  black_level: 64.0
  enable: true
ccm:
  enable: true
  highlight_threshold: 0.7
  matrix:
  - - 1.2
    - -0.1
    - -0.1
  - - -0.05
    - 1.2
    - -0.15
  - - 0.0
    - -0.1
    - 1.1
  saturation_boost: 1.8
chroma_denoise:
  chroma_strength: 0.7
  enable: false
  luma_threshold: 0.2
  strength: 0.8
  threshold: 0.1
color_space_conversion:
  enable: false
  gamut_mapping: compress
  input_space: sRGB
  output_space: rec2020
demosaic:
  bayer_pattern: rggb
  edge_threshold: 50
  enable: true
  gradient_weight: 0.7
  method: frequency_domain
  preserve_edges: true
denoise:
  enable: false
  preserve_edges: true
  strength: 1.0
denoise_clip:
  clip_threshold: 0.95
  enable: false
  threshold: 10
dpc:
  enable: true
  method: median
  threshold: 5.0
exposure_compensation:
  enable: false
  highlight_compression: 0.7
  highlight_threshold: 0.95
  manual_gain: 1.0
  mode: auto
  target_brightness: 0.6
  target_percentile: 85
fisheye_mask:
  center: '[1456, 1456]'
  enable: false
  radius: 1456
gamma:
  curve_type: s_curve
  enable: true
  gamma: 2.2
  midtone_boost: 0.05
  value: 2.2
lsc:
  enable: true
  focal_length_mm: 4.0
  model_type: cosine_fourth
  pixel_size_um: 1.4
  strength: 0.3
noise_estimation:
  dark_threshold: 0.1
  enable: false
output:
  debug_dir: D:/Code/ISP_Framework/image\debug
  dither_strength: 0.5
  output_dir: D:/Code/ISP_Framework/image\output
  path: output/result.png
raw:
  height: 2048
  input_dir: D:/Code/ISP_Framework/image
  raw_to_16bit_scale_factor: 64
  sensor_bit_depth: 10
  width: 2048
shadow_highlight:
  enable: false
  highlight_amount: 0
  highlight_roll: 0.8
  shadow_amount: 0
  shadow_lift: 0.1
sharpen:
  blur_kernel_size: 3
  enable: false
  method: unsharp_masking
  radius: 1.0
  strength: 1.5
  threshold: 0.1
super_resolution:
  enable: false
  method: bicubic
  scale_factor: 2.0
  sharpen_amount: 0.8
  sharpen_enable: true
  sharpen_radius: 1.0
  upscale_method: bicubic
tonemapping:
  brightness: 1.05
  compress: 0.45
  contrast: 1.1
  enable: true
  lift: 0.1
  method: reinhard
  roll: 0.8
wb:
  b_gain: 1.0
  enable: true
  g_gain: 1.0
  gains:
  - 1.5
  - 1.0
  - 1.3
  max_gain: 3.0
  method: gray_world
  min_gain: 0.3
  r_gain: 1.0
  wb_max_luminance_threshold: 0.99
  wb_min_luminance_threshold: 0.05
  white_patch_percentile: 99.5
