# 文件：config.yaml（请放置在项目根目录） """ # 这是配置文件，控制每个处理模块是否启用，以及它们的参数。 # 新手建议：通过修改这个文件来测试不同处理效果。 
 raw:   
  path: "./1920x1080.raw"  # 输入 RAW 图像路径   
  width: 1920 
  height: 1080
  sensor_bit_depth: 10
  raw_to_16bit_scale_factor: 64 # 例如，如果你的 RAW 是 10-bit，这里填 64
  bayer_pattern: "rggb" 


 blc:  # 黑电平校正（Black Level Correction）   
  enable: true   
  black_level: 64 


 lsc:
  enable: true
  # LSC 模型类型：
  # 'linear': 简单的线性增益 (1 + strength * distance)
  # 'quadratic': 二次函数增益 (1 + strength * distance^2) - 推荐，更平滑
  # 'cosine_fourth': 余弦四次方近似增益 (1 + strength * distance^4) - 模拟更真实的晕影
  model_type: quadratic 
  # 增益强度：值越大，边缘提亮越多
  strength: 0.3 # 0.1 到 0.5 之间通常比较合适
  # 如果你使用了 cosine_fourth 模型，可能需要调整这个 K 值
  # cosine_fourth_k: 0.5 
  # 用于 LSC 裁剪的上限值。
  # 应该与 demosaic 中使用的 `max_raw_sensor_value_mapped_to_uint16` 相同
  # 如果你的 raw_loader 读出的是 uint16，且已左移填充，那么填 65472 或 65535
  # max_value_for_clip: 65472 # (可选，如果 raw_to_16bit_scale_factor 导致最大值改变)


 demosaic: #去马赛克
  enable: true   
  method: "opencv" 
  # 这个值至关重要！它应该是你的 RAW 传感器数据在被读取并转换为 uint16 后，
  # 能够达到的最大理论值。
  # 如果是 10bit RAW 左移 6bit 存入 uint16，那么这里就是 1023 * (2**6) = 65472
  # 如果是 12bit RAW 左移 4bit 存入 uint16，那么这里就是 4095 * (2**4) = 65520
  # 如果是标准的 16bit RAW，那么就是 65535
   # 请根据你的原始 RAW 数据的实际位深来设置此值。



 wb:   # 白平衡（White Balance）   
  enable: true
  # White balance method: 'manual', 'gray_world', 'max_rgb'
  method: gray_world 
  # 如果 method 是 'manual'，则使用下面的 gains
  gains: [1.0, 1.0, 1.0] 
  # 如果是 'gray_world' 或 'max_rgb'，这些 gains 会被覆盖


 denoise:  #去噪
  enable: true
  # 去噪方法：'gaussian', 'bilateral', 'median', 'nl_means'
  method:  nl_means 
  # 高斯模糊和中值滤波参数
  kernel_size: 7 # 必须是奇数，如 3, 5, 7, ...
  sigma_x: 0    # 高斯模糊X方向标准差，0表示根据核大小计算
  # 双边滤波参数 (如果 method 为 'bilateral')
  diameter: 7       # 邻域直径
  sigma_color: 50   # 颜色相似度标准差 (0-255)
  sigma_space: 50   # 空间相似度标准差 (0-255)
  # 'nl_means' (非局部均值) 参数
  h_param: 3       # 关键强度参数。值越大，去噪越强，但细节损失也越大。从 10-20 之间尝试。
  h_color_param: 3 # 颜色强度参数，通常与 h_param 相同。
  template_window_size: 7 # 小窗口，用于定义补丁（patch）
  search_window_size: 21  # 大窗口，用于搜索相似补丁的范围




 ccm:  # 颜色矩阵（Color Correction Matrix）   
  enable: true   
  matrix: [[1.5, -0.3, -0.2],            
           [-0.2, 1.3, -0.1],            
           [0.0, -0.6, 1.6]] 


 
  
 gamma:  # Gamma 校正   
  enable: true   
  value: 2.2 



 tonemapping:
  enable: true
  lift: 0.01
  roll: 0.8
  compress: 0.5
 




 sharpen:  #锐化
  enable: true
  # 锐化方法：'unsharp_masking' (目前只实现了这一种)
  method: unsharp_masking 
  # 非锐化掩蔽参数
  blur_kernel_size: 3 # 用于生成模糊图像的核大小，必须是奇数，如 3, 5, 7, ...
  strength: 1.5      # 锐化强度，通常 0.5 到 2.0 之间。过大会产生光晕或噪声



 output:   
  path: "output/result.png"      # 最终输出图像路径   
  debug_dir: "output/"           # 每个步骤的中间图保存目录 """
  dither_strength: 0.5 # 抖动强度，通常在 0.5 到 1.0 之间尝试。设置为 0 则禁用抖动。